apiVersion: v1
kind: ConfigMap
metadata:
  name: gce-config
  labels:
    name: gce-config
data:
  SELENIUM_SERVER: http://halSelenium/wd/hub
  HAL_ENDPOINT: http://hal-service
---
kind: Service
apiVersion: v1
metadata:
  name: gce-monitor
spec:
  selector:
    app: gce-monitor
  ports:
  - protocol: TCP
    name: http
    port: 80
    targetPort: 8001
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gce-monitor-ingress
  annotations:
    kubernetes.io/ingress.class: istio
spec:
  rules:
  - host: gce-monitor.legion.sbsa.local
    http:
      paths:
      - backend:
          serviceName: gce-monitor-service
          servicePort: http

